version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spaceit
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_NAME: spaceit
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]

  celery:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - web
      - redis
    environment:
      DATABASE_NAME: spaceit  # Matching the web service
      DATABASE_USER: root  # Matching the web service
      DATABASE_PASSWORD: root  # Matching the web service
      DATABASE_HOST: db  # Matching the web service
      DATABASE_PORT: 3306  # Matching the MySQL port
      CELERY_BROKER_URL: redis://redis:6379/0  # Correct broker URL for Celery
    command: ["celery", "-A", "myproject", "worker", "--loglevel=info"]

volumes:
  mysql_data:
