# Generated by Django 5.1.5 on 2025-01-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.FloatField(help_text='Distance in Astronomical Units (AU)')),
                ('link_to_image', models.URLField()),
            ],
        ),
    ]
