# Generated by Django 5.1.5 on 2025-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='cargo_capacity_kg',
            field=models.FloatField(help_text='kgs'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='fuel_capacity',
            field=models.FloatField(help_text='tonnes'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='range_au',
            field=models.FloatField(editable=False, help_text='AUs'),
        ),
    ]
