# Generated by Django 5.1.5 on 2025-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0002_alter_rocket_cargo_capacity_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, help_text='£ per tonne', max_digits=10),
        ),
    ]
